# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fargo < Formula
  desc "fargo is a CLI interface to Farcaster written in Go."
  homepage "https://github.com/vrypan/fargo"
  version "0.1.17"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/vrypan/fargo/releases/download/0.1.17/fargo_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "a22a8c9538da6f82a6cb0d936b8f161731b6b4b518bc8ec32cf1051e5cedbfb1"

      def install
        bin.install "fargo"
      end
    end
    on_arm do
      url "https://github.com/vrypan/fargo/releases/download/0.1.17/fargo_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "2e4e675f47f254337d32c8891ceaade5d0e2fa72a90c94c7261dc574618c70a8"

      def install
        bin.install "fargo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vrypan/fargo/releases/download/0.1.17/fargo_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "b1ffc9292d452f24a9d5f02b162ca14c2e410bfb14d1e3c9a74b434c6ee8f7ad"

        def install
          bin.install "fargo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vrypan/fargo/releases/download/0.1.17/fargo_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "a466c0806f53dae5d47cfe1ac372f257aabb7dbc9b3784bb8aece418eb441f43"

        def install
          bin.install "fargo"
        end
      end
    end
  end

  def caveats
    <<~EOS
      fargo --help
    EOS
  end

  test do
    system "#{bin}/fargo version"
  end
end
