# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fargo < Formula
  desc "fargo is a CLI interface to Farcaster written in Go."
  homepage "https://github.com/vrypan/fargo"
  version "0.1.14"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/vrypan/fargo/releases/download/0.1.14/fargo_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "035dea4d072a6d46ad15ee214f15bf7dc59941e662b9e5283d9656cad5f5a465"

      def install
        bin.install "fargo"
      end
    end
    on_arm do
      url "https://github.com/vrypan/fargo/releases/download/0.1.14/fargo_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "12c1c0019d0d68c5709c01bfa9feaf28d0d8011d1148d32b02dc84533930a99e"

      def install
        bin.install "fargo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vrypan/fargo/releases/download/0.1.14/fargo_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "9cca094b40b6e057f6841eaeb73ff0ce4631c64eca7e44e03ae66eef713308e5"

        def install
          bin.install "fargo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vrypan/fargo/releases/download/0.1.14/fargo_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "e4c42416ea941a3a6f27344a78e20f1952f676e8d3dc8d6cbc4dc718b4eab9da"

        def install
          bin.install "fargo"
        end
      end
    end
  end

  def caveats
    <<~EOS
      fargo --help
    EOS
  end

  test do
    system "#{bin}/fargo version"
  end
end
